spring:
  profiles:
    active: dev
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  # todo 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_oj
    username: root
    password: 123456
  # todo 配置Redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
# 配置运行端口
server:
  port: 8081
  servlet:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# 阿里云OSS配置
aliyun:
  # todo 记得修改成自己的阿里云配置
  access-key-id: your_access_key_id
  endpoint: "https://oss-cn-beijing.aliyuncs.com"
  secret-access-key: your_access_key_secret
  bucket-name: your_bucket_name

# mybatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null


# 接口文档配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.cre.oj.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
